setwd('/home/joand/Desktop/Kaggle/cat-in-the-dat-ii')
install.packages('data.table')
install.packages('arules')
library(data.table)
library(arules)
df <- read.csv('df_ok.csv')
df$bin_0 <- as.factor(df$bin_0)
df$bin_1 <- as.factor(df$bin_1)
df$bin_2 <- as.factor(df$bin_2)
df$ord_0 <- as.factor(df$ord_0)
df$day <- as.factor(df$day)
df$month <- as.factor(df$month)
tData <- as (df, "transactions") # convert to 'transactions' class
rules <- apriori (tData, parameter = list(supp = 0.001, conf = 0.001, maxlen = 1,  target = 'rules'))
inspect(rules)
df_rules <- as(rules, "data.frame")
View(df_rules)
write.csv(df_rules,'df_rules_L_1.csv')
  x <- interestMeasure(rules, c("addedValue", "oddsRatio", "leverage"), 
                    transactions = tData)
View(x)
